#!/usr/bin/env node
// The ONLY writer of tools-manifest.json (see vice-proxy.mjs's tools/list
// handler doc comment -- that handler is a pure, offline READ of the file
// this CLI produces). An operator runs this by hand against a running host
// to refresh the snapshot; vice-proxy.mjs never imports this file, so this
// file's stdout is a normal CLI stream, not the MCP channel.
//
// Sibling import: the transport module lives in this skill's own scripts/
// directory (plan 01.1-04 relocated it from the now-retired `vice-session`
// skill).
import { serverInfo, activeInstance, type ServerInfoPayload, type ToolInfo } from "./vice.ts";
import { writeFileSync, chmodSync, renameSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_MANIFEST_PATH = join(HERE, "tools-manifest.json");

function manifestPath(): string {
  return process.env.VICE_TOOLS_MANIFEST
    ? resolve(process.env.VICE_TOOLS_MANIFEST)
    : DEFAULT_MANIFEST_PATH;
}

export interface ToolsManifest {
  generated_at: string;
  endpoint: string;
  tools: ToolInfo[];
}

/** Write `manifest` to `path` via the tmp sibling -> restrict-mode -> content
 * -> rename sequence (01.6.1-06 Decision 1), copied verbatim in shape from
 * vice-broker.mts's writeBrokerRecord(). The tmp file is created EMPTY and
 * mode-tightened to 0o600 BEFORE any content reaches it, then renamed into
 * place -- so a crash or a full disk mid-write can only ever leave a stray
 * tmp sibling behind, never a partial or empty file at the real path. This
 * is what makes this module's own long-standing promise ("a partial or
 * empty manifest is never written over a good one on failure") true against
 * a crash, not only against a rejected handshake -- the rejected-handshake
 * half of that guarantee already held (the early return below, unchanged
 * from the original), but a crash between "open the file" and "write the
 * content" could previously still truncate a good manifest to nothing. */
function writeManifestAtomic(path: string, manifest: ToolsManifest): void {
  const tmpPath = `${path}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmpPath, "");
  chmodSync(tmpPath, 0o600);
  writeFileSync(tmpPath, JSON.stringify(manifest, null, 2) + "\n");
  renameSync(tmpPath, path);
}

/** Parses no arguments (there are none), performs the host handshake, and
 * writes the manifest -- or leaves the existing one untouched and sets a
 * non-zero exit code if the handshake fails. Exported (01.6.1-06 Decision 2)
 * so this can be driven directly in a test without spawning a process; the
 * bottom-of-module entry-point guard below is what makes that safe -- import
 * alone must never perform a handshake or write anything. */
export async function main(): Promise<void> {
  const path = manifestPath();

  // serverInfo() performs the host handshake (initialize + tools/list) and
  // already strips DENY_LIST names before returning (vice.ts's own
  // documented choke point) -- vice-proxy.mjs's tools/list handler applies
  // the SAME filter again at read time, so a snapshot generated by any other
  // means is still safe, but this refresh path inherits the omission for
  // free.
  let info: ServerInfoPayload;
  try {
    info = (await serverInfo()) as ServerInfoPayload;
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    console.error(
      `refresh-manifest: could not reach the host VICE MCP server (${message}) -- ` +
        `manifest at ${path} left UNCHANGED. A partial or empty manifest is never written over a good one on ` +
        `failure -- whether the failure is a rejected handshake (this path) or a crash mid-write, the latter now ` +
        `also covered by the tmp-sibling -> restrict-mode -> content -> rename sequence below.`
    );
    process.exitCode = 1;
    return;
  }

  const tools = Array.isArray(info?.tools) ? info.tools : [];
  const manifest: ToolsManifest = {
    generated_at: new Date().toISOString(),
    endpoint: activeInstance().url,
    tools,
  };

  writeManifestAtomic(path, manifest);
  console.log(`refresh-manifest: wrote ${tools.length} tool${tools.length === 1 ? "" : "s"} to ${path}`);
}

// -------------------------------------------------------------------- CLI
// Guarded exactly like vice-broker.mts's own entry point: importing this
// module (e.g. from a test) must never itself perform a handshake or write
// anything. process.exitCode, never process.exit(), so any pending I/O
// flushes first.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((e: unknown) => {
    const detail = e instanceof Error && e.stack ? e.stack : String(e);
    console.error(`refresh-manifest: unexpected error -- ${detail}`);
    process.exitCode = 1;
  });
}
