#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${CLAUDE_CONFIG_DIR:-${HOME}/.claude}"
SETTINGS_FILE="${CONFIG_DIR}/settings.json"
CLAUDE_MD="${CONFIG_DIR}/CLAUDE.md"

BLOCK_START="<!-- BEGIN MANAGED PR-MR-POLICY -->"
BLOCK_END="<!-- END MANAGED PR-MR-POLICY -->"

info() {
    printf '\n==> %s\n' "$*"
}

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

mkdir -p "$CONFIG_DIR"

# ---------------------------------------------------------------------------
# Claude Code settings
# ---------------------------------------------------------------------------

update_settings() {
    local file="$1"
    local tmp

    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' RETURN

    if command -v node >/dev/null 2>&1; then
        SETTINGS_FILE="$file" node <<'NODE' >"$tmp"
const fs = require("fs");

const file = process.env.SETTINGS_FILE;
let settings = {};

if (fs.existsSync(file)) {
    const text = fs.readFileSync(file, "utf8").trim();

    if (text) {
        try {
            settings = JSON.parse(text);
        } catch (err) {
            console.error(`Cannot parse ${file}: ${err.message}`);
            process.exit(1);
        }
    }
}

settings.attribution = {
    ...(settings.attribution || {}),
    commit: "",
    pr: ""
};

process.stdout.write(JSON.stringify(settings, null, 2) + "\n");
NODE

    elif command -v jq >/dev/null 2>&1; then
        if [[ -s "$file" ]]; then
            jq '
                .attribution = ((.attribution // {}) + {
                    "commit": "",
                    "pr": ""
                })
            ' "$file" >"$tmp"
        else
            jq -n '{
                attribution: {
                    commit: "",
                    pr: ""
                }
            }' >"$tmp"
        fi

    else
        die "Node.js or jq is required to update $file"
    fi

    mv "$tmp" "$file"
    trap - RETURN
}

# ---------------------------------------------------------------------------
# CLAUDE.md managed block
# ---------------------------------------------------------------------------

update_claude_md() {
    local file="$1"
    local tmp

    tmp="$(mktemp)"

    if [[ -f "$file" ]]; then
        awk \
            -v start="$BLOCK_START" \
            -v end="$BLOCK_END" '
            $0 == start { inside=1; next }
            $0 == end   { inside=0; next }
            !inside     { print }
        ' "$file" >"$tmp"
    else
        : >"$tmp"
    fi

    # Remove blank lines at the end before we append the managed block.
    while [[ -s "$tmp" ]] && [[ -z "$(tail -n 1 "$tmp")" ]]; do
        sed -i '$d' "$tmp"
    done

    if [[ -s "$tmp" ]]; then
        printf '\n\n' >>"$tmp"
    fi

    cat >>"$tmp" <<'EOF'
<!-- BEGIN MANAGED PR-MR-POLICY -->
## Pull requests and merge requests

Write concise PR and MR descriptions.

State what changed and why it changed.

State how you tested the change when testing is relevant.

Use one short summary paragraph.

Use up to four bullets when bullets improve clarity.

Keep most descriptions between 50 and 120 words.

Use fewer words for small changes.

Do not describe every changed file.

Do not repeat information that is clear from the diff.

Do not write a long implementation narrative.

Do not include large test logs.

Do not add unnecessary headings, tables, checklists, or boilerplate.

Do not include internal reasoning or a step-by-step development history.

When the repository provides a PR or MR template, use the template.

Keep each template section concise.

## AI attribution

Do not add statements that identify Claude, Claude Code, Anthropic, or another
AI as an author or contributor.

Do not add AI attribution to commits, PRs, MRs, issues, release notes,
documentation, or code comments.

Do not add:

- `Generated with Claude Code`
- `Created by Claude`
- `Generated by AI`
- `AI-assisted`
- Claude session URLs
- Claude or AI signatures
- `Co-Authored-By` trailers that identify Claude or AI

Do not add an authorship statement unless the user or repository requires one.
<!-- END MANAGED PR-MR-POLICY -->
EOF

    mv "$tmp" "$file"
}

info "Installing Claude Code PR/MR policy"
printf 'Claude config: %s\n' "$CONFIG_DIR"

update_settings "$SETTINGS_FILE"
update_claude_md "$CLAUDE_MD"

info "Installation complete"

cat <<EOF

Updated:

  $SETTINGS_FILE
    - Claude commit attribution disabled
    - Claude PR attribution disabled

  $CLAUDE_MD
    - concise PR/MR policy installed
    - AI attribution prohibited

The script is safe to run again.
It replaces only this managed block:

  $BLOCK_START
  ...
  $BLOCK_END

Existing CLAUDE.md content and unrelated settings are preserved.

EOF
