#!/usr/bin/env node
// hazard-subject-fixture.test.ts -- the purpose-built hazard-subject fixture's
// own assertion file.
//
// WHY THIS FILE EXISTS
// ---------------------------------------------------------------------------
// `fixtures/hazard-subject/` grows a committed synthetic C64 program that
// deliberately plants non-canonical movement-hazard constructions -- shapes a
// real detector accepts but that differ from this project's own shipped test
// corpus, plus at least one shape a detector correctly DECLINES. Every
// assertion here names the byte-level construction the fixture's source
// actually contains, never a detector's opinion of it -- the fixture is
// evidence a detector is measured AGAINST, and a test that asserted "the
// detector says X" instead of "the bytes are X" would let the fixture and the
// detector drift into agreeing with each other for the wrong reason.
//
// Every test in this file re-derives the committed `.prg`(s) from their
// committed `.a` sources and either reads the regenerated bytes directly or
// cross-checks them against the committed file -- a hand-edited image can
// never silently become "the thing under test" here.
//
// Test names carry the `hazard subject:` prefix throughout, per the plan.
//
// GATE
// ---------------------------------------------------------------------------
// Exactly one test always runs and is never skipped: "ACME availability
// gate". With `VICE_REQUIRE_ACME` set (CI's Test step) a missing ACME FAILS
// that test. Locally, with no ACME on PATH, every other ACME-dependent test
// skips with a named reason computed ONCE by the shared `acme-gate.ts` seam
// -- never a hand-rolled probe.

import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ACME_BIN, acmeSkipReasonFor, assertAcmeRequiredIfEnvSet } from "./acme-gate.ts";
import { decode, type Instruction } from "./disasm-decoder.ts";
import { scanIndirectDispatch } from "./anno-coverage.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = join(HERE, "fixtures", "hazard-subject");
const ROOT_SOURCE_PATH = join(FIXTURE_DIR, "hazard-subject.a");
const ROOT_SOURCE_NAME = "hazard-subject.a";
const DISPATCH_SOURCE_PATH = join(FIXTURE_DIR, "hazard-subject-dispatch.a");
const ALIGN_SOURCE_PATH = join(FIXTURE_DIR, "hazard-subject-align.a");
const PRG_PATH = join(FIXTURE_DIR, "hazard-subject.prg");

const SKIP_REASON = acmeSkipReasonFor("hazard-subject-fixture.test.ts");

test("ACME availability gate", () => {
  assertAcmeRequiredIfEnvSet(assert);
});

/** Splits a committed `.prg`'s two-byte little-endian load address from its
 * payload, the same way every consumer in this tree does. */
function loadPrg(path: string): { bytes: Uint8Array; origin: number } {
  const raw = readFileSync(path);
  const origin = raw[0]! | (raw[1]! << 8);
  return { bytes: new Uint8Array(raw.subarray(2)), origin };
}

/** Re-derives `decoded is Instruction` locally rather than importing
 * `anno-coverage.ts`'s own private `isDecodableAsInstruction` (unexported by
 * design): a legal, non-truncated decode at `address`. */
function isLegalInstructionStart(bytes: Uint8Array, origin: number, address: number): boolean {
  if (address < origin) return false;
  const offset = address - origin;
  if (offset < 0 || offset >= bytes.length) return false;
  const decoded: Instruction | undefined = decode(bytes.subarray(offset), address, { count: 1 })[0];
  return !!decoded && !decoded.illegal && !decoded.notes.includes("truncated");
}

/** Assembles `rootSourceName` (resolved with `cwd: FIXTURE_DIR`, so its own
 * bare-filename `!source` lines resolve exactly as the committed regenerator
 * resolves them) fresh into a throwaway directory, never touching the
 * committed `.prg`. Returns the raw bytes ACME wrote, load address included. */
function assembleFresh(rootSourceName: string): Uint8Array {
  const dir = mkdtempSync(join(tmpdir(), "hazard-subject-fixture-"));
  try {
    const outPath = join(dir, "out.prg");
    const r = spawnSync(ACME_BIN, ["--cpu", "6510", "-f", "cbm", "-o", outPath, rootSourceName], {
      encoding: "utf8",
      timeout: 30_000,
      cwd: FIXTURE_DIR,
    });
    assert.equal(r.status, 0, `${rootSourceName} must assemble:\n  stderr: ${r.stderr ?? ""}`);
    assert.equal(existsSync(outPath), true, "ACME must write an output file");
    return new Uint8Array(readFileSync(outPath));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// hazard subject: class 1 -- the planted non-canonical stack-return dispatch,
// and the mixed-index-register construction the scanner correctly declines.
// ---------------------------------------------------------------------------

test("hazard subject: the imported scanner proves at least one stack-return dispatch finding on the committed image, with the scan's own truncation flag false", { skip: SKIP_REASON }, () => {
  const { bytes, origin } = loadPrg(PRG_PATH);
  const instructions = decode(bytes, origin);
  const scan = scanIndirectDispatch(instructions, bytes, origin);
  assert.ok(
    scan.stackReturnDispatch.length >= 1,
    "the committed image must carry at least one PROVEN stack-return dispatch finding -- the planted non-canonical construction",
  );
  assert.equal(scan.truncated, false, "the scan must not have been cut short reconstructing the planted subject");
});

test("hazard subject: every target the stack-return finding reconstructs is a real instruction start inside the committed image", { skip: SKIP_REASON }, () => {
  const { bytes, origin } = loadPrg(PRG_PATH);
  const instructions = decode(bytes, origin);
  const scan = scanIndirectDispatch(instructions, bytes, origin);
  assert.ok(scan.stackReturnDispatch.length >= 1, "precondition: at least one proven finding must exist to check its targets");
  for (const finding of scan.stackReturnDispatch) {
    assert.ok(finding.targets.length > 0, "a proven finding must reconstruct at least one target");
    for (const target of finding.targets) {
      assert.ok(
        isLegalInstructionStart(bytes, origin, target),
        `reconstructed target $${target.toString(16)} must decode as a legal, non-truncated instruction inside the image`,
      );
    }
  }
});

test("hazard subject: the mixed-index-register declining control appears in no proven collection -- only as an unproven, unresolved candidate", { skip: SKIP_REASON }, () => {
  const { bytes, origin } = loadPrg(PRG_PATH);
  const instructions = decode(bytes, origin);
  const scan = scanIndirectDispatch(instructions, bytes, origin);

  // Exactly one PROVEN stack-return finding -- the mixed-register site never
  // promotes to a second one, and no zeropage-vector-gated split table exists
  // in this subject either.
  assert.equal(scan.stackReturnDispatch.length, 1, "the mixed-index-register site must not be promoted into a second proven stack-return finding");
  assert.equal(scan.splitTables.length, 0, "this subject plants no zeropage-vector-gated split table -- a non-zero count here would mean the declining site was proven some other way");

  // The declining pairing shows up ONLY as an advisory candidate: no
  // orientation claim, no targets.
  assert.ok(scan.splitTableCandidates.length >= 1, "the mixed-index-register pairing must be recorded as an unproven, advisory candidate");
  for (const candidate of scan.splitTableCandidates) {
    assert.equal(candidate.orientationResolved, false, "an advisory candidate must carry no orientation claim");
    assert.equal(candidate.targets.length, 0, "an advisory candidate must reconstruct no targets");
  }
});

test("hazard subject: the dispatch routine's two paired loads walk the Y register, never X; the declining control walks X on one load and Y on the other", () => {
  const rootSource = readFileSync(ROOT_SOURCE_PATH, "utf8");
  const dispatchSource = readFileSync(DISPATCH_SOURCE_PATH, "utf8");

  assert.ok(rootSource.includes("dispatch_hi,y"), "the proven site's first load must index dispatch_hi through Y");
  assert.ok(rootSource.includes("dispatch_lo,y"), "the proven site's second load must index dispatch_lo through Y");
  assert.ok(!/,\s*x\b/i.test(rootSource), "the root file must contain no X-indexed load at all -- the proven site never uses X");

  assert.ok(dispatchSource.includes("decline_hi,x"), "the declining control's first load must index decline_hi through X");
  assert.ok(dispatchSource.includes("decline_lo,y"), "the declining control's second load must index decline_lo through Y");
});

test("hazard subject: every entry in both split address tables is written as a label followed by an explicit -1", () => {
  const dispatchSource = readFileSync(DISPATCH_SOURCE_PATH, "utf8");
  const provenTablesBlock = dispatchSource.slice(dispatchSource.indexOf("dispatch_hi"), dispatchSource.indexOf("decline_hi"));
  assert.ok(provenTablesBlock.length > 0, "precondition: dispatch_hi must precede decline_hi in the source");
  const biasedEntries = provenTablesBlock.match(/dispatch_target_\d+-1\)/g) ?? [];
  assert.equal(
    biasedEntries.length,
    6,
    "the proven site's two tables (dispatch_hi, dispatch_lo) must together carry exactly six explicit `label-1` entries -- three targets, high byte and low byte each",
  );
});

test("hazard subject: no fixture source in this tree names the scanner it is planted against", () => {
  const dispatchSource = readFileSync(DISPATCH_SOURCE_PATH, "utf8");
  const stripped = dispatchSource
    .split("\n")
    .filter((line) => !/^\s*;/.test(line))
    .join("\n");
  assert.ok(!stripped.includes("scanIndirectDispatch"), "the dispatch fixture source must never name the scanner it is planted against");
});

test("hazard subject: the root source carries exactly three bare-filename !source lines", () => {
  const rootSource = readFileSync(ROOT_SOURCE_PATH, "utf8");
  const sourceLines = rootSource.match(/^!source\s+"[^"/\\]+"\s*$/gm) ?? [];
  assert.equal(sourceLines.length, 3, "the root must carry exactly three !source lines after the dispatch and alignment constructions are both added, each a bare filename");
});

test("hazard subject: no planning-vocabulary string appears anywhere in the dispatch fixture source", () => {
  const dispatchSource = readFileSync(DISPATCH_SOURCE_PATH, "utf8");
  assert.ok(!dispatchSource.includes(".planning/"), "must not reference a .planning/ path");
  assert.ok(!/\/gsd-/.test(dispatchSource), "must not reference a /gsd- command name");
  assert.ok(!/\bD-\d/.test(dispatchSource), "must not carry a bare D-NN decision id");
  assert.ok(!/\bBUILD-\d/.test(dispatchSource), "must not carry a BUILD-NN requirement id");
  assert.ok(!/\bPhase\s+\d/.test(dispatchSource), "must not carry a 'Phase N' citation");
});

/** Assembles `rootSourceName` fresh (same discipline as `assembleFresh()`)
 * AND asks ACME for a symbol list, so a test can check a real label's
 * ASSEMBLED address rather than reading it out of the source text. Returns
 * `null` for a symbol name it did not find, never throws. */
function assembleFreshWithSymbols(rootSourceName: string): { bytes: Uint8Array; symbols: Map<string, number> } {
  const dir = mkdtempSync(join(tmpdir(), "hazard-subject-fixture-sym-"));
  try {
    const outPath = join(dir, "out.prg");
    const symPath = join(dir, "out.sym");
    const r = spawnSync(ACME_BIN, ["--cpu", "6510", "-f", "cbm", "-o", outPath, "--symbollist", symPath, rootSourceName], {
      encoding: "utf8",
      timeout: 30_000,
      cwd: FIXTURE_DIR,
    });
    assert.equal(r.status, 0, `${rootSourceName} must assemble:\n  stderr: ${r.stderr ?? ""}`);
    assert.equal(existsSync(outPath), true, "ACME must write an output file");
    assert.equal(existsSync(symPath), true, "ACME must write a symbol list file");
    const symbols = new Map<string, number>();
    for (const line of readFileSync(symPath, "utf8").split("\n")) {
      const m = line.match(/^\s*(\S+)\s*=\s*\$([0-9a-fA-F]+)/);
      if (m) symbols.set(m[1]!, parseInt(m[2]!, 16));
    }
    return { bytes: new Uint8Array(readFileSync(outPath)), symbols };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// hazard subject: class 3 -- the planted VIC-II hardware alignment
// dependency, and the four data tables the export path needs.
// ---------------------------------------------------------------------------

test("hazard subject: the sprite shape base address is a multiple of 64, and the character-set base address is a multiple of 2048 -- asserted against the assembled image", { skip: SKIP_REASON }, () => {
  const { symbols } = assembleFreshWithSymbols(ROOT_SOURCE_NAME);
  const spriteBase = symbols.get("align_sprite_base");
  const charBase = symbols.get("align_char_base");
  assert.ok(spriteBase !== undefined, "align_sprite_base must be a real symbol in the assembled image");
  assert.ok(charBase !== undefined, "align_char_base must be a real symbol in the assembled image");
  assert.equal(spriteBase! % 64, 0, `align_sprite_base ($${spriteBase!.toString(16)}) must be 64-byte aligned`);
  assert.equal(charBase! % 2048, 0, `align_char_base ($${charBase!.toString(16)}) must be 2048-byte aligned`);
});

test("hazard subject: the byte written to $07f8 equals the sprite base divided by 64", { skip: SKIP_REASON }, () => {
  const { bytes, symbols } = assembleFreshWithSymbols(ROOT_SOURCE_NAME);
  const spriteBase = symbols.get("align_sprite_base")!;
  const origin = bytes[0]! | (bytes[1]! << 8);
  const payload = bytes.subarray(2);
  const instructions = decode(payload, origin);
  const storeIndex = instructions.findIndex((insn) => insn.mnemonic === "sta" && insn.operand?.value === 0x07f8);
  assert.ok(storeIndex > 0, "the image must contain an `sta $07f8` instruction");
  const loader = instructions[storeIndex - 1]!;
  assert.equal(loader.mnemonic, "lda", "the instruction immediately before `sta $07f8` must be the `lda #imm` that loads the pointer byte");
  assert.equal(loader.operand?.role, "immediate", "the sprite pointer must be loaded as an immediate value");
  assert.equal(loader.operand!.value, Math.floor(spriteBase / 64), "the byte written to $07f8 must equal the sprite base divided by 64");
});

test("hazard subject: four distinct labelled data tables exist -- sprite shape, character set, level and music", () => {
  const alignSource = readFileSync(ALIGN_SOURCE_PATH, "utf8");
  for (const label of ["align_sprite_base", "align_char_base", "align_level_table", "align_music_table"]) {
    assert.ok(new RegExp(`^${label}\\b`, "m").test(alignSource), `${label} must be declared as its own label in the alignment source`);
  }
  const dataDirectives = alignSource.match(/^\s*!(byte|fill)\b/gm) ?? [];
  assert.ok(dataDirectives.length >= 4, "each of the four tables must carry at least one data directive");
});

test("hazard subject: the alignment source carries an explicit alignment directive for both the sprite shape block and the character-set block", () => {
  const alignSource = readFileSync(ALIGN_SOURCE_PATH, "utf8");
  const alignDirectives = alignSource.match(/^\s*!align\b/gm) ?? [];
  assert.equal(alignDirectives.length, 2, "exactly two !align directives are expected -- one for the character set, one for the sprite shape");
});

test("hazard subject: the sprite pointer and the VIC memory-control bits are derived from their labels, never written as bare hex constants", () => {
  const alignSource = readFileSync(ALIGN_SOURCE_PATH, "utf8");
  assert.ok(alignSource.includes("align_sprite_base / 64"), "the $07f8 write must derive its value from align_sprite_base, not a literal");
  assert.ok(alignSource.includes("align_char_base / 2048"), "the $d018 write must derive its value from align_char_base, not a literal");
});

test("hazard subject: no planning-vocabulary string appears anywhere in the alignment fixture source", () => {
  const alignSource = readFileSync(ALIGN_SOURCE_PATH, "utf8");
  assert.ok(!alignSource.includes(".planning/"), "must not reference a .planning/ path");
  assert.ok(!/\/gsd-/.test(alignSource), "must not reference a /gsd- command name");
  assert.ok(!/\bD-\d/.test(alignSource), "must not carry a bare D-NN decision id");
  assert.ok(!/\bBUILD-\d/.test(alignSource), "must not carry a BUILD-NN requirement id");
  assert.ok(!/\bPhase\s+\d/.test(alignSource), "must not carry a 'Phase N' citation");
});

test("hazard subject: REGENERATOR AGREEMENT -- re-assembling the root reproduces the committed hazard-subject.prg byte-for-byte", { skip: SKIP_REASON }, () => {
  const fresh = assembleFresh(ROOT_SOURCE_NAME);
  assert.deepEqual(
    [...fresh],
    [...new Uint8Array(readFileSync(PRG_PATH))],
    "hazard-subject.a (plus its !source parts) and hazard-subject.prg have drifted apart. The committed image is only evidence while it is EXACTLY what its " +
      "source assembles to; regenerate with `cd src/mcp/vice && node fixtures/hazard-subject/make-hazard-subject-fixtures.mjs`.",
  );
});
