// vsf-slice.test.ts
//
// The committed regression for `vsf-slice.ts`: the end-to-end slice of a
// well-formed snapshot, plus a structural check that the module really is the
// pure, I/O-free, imports-nothing thing its header claims.
//
// WHY THE FIXTURES ARE SYNTHETIC AND SAY SO: no corpus byte, snapshot or
// capture image is ever committed to this repository. The four fixtures under
// `fixtures/vsf/` are generated by `fixtures/vsf/make-fixtures.mjs`, each
// carries a `"synthetic": true` provenance sidecar naming that generator, and
// their LAYOUT is modelled byte-for-byte on the measured layout of a genuine
// VICE 3.9 snapshot. A synthetic fixture claiming to be a capture would be
// worse than no fixture at all.
//
// WHY THE RAM PATTERN IS RECOMPUTED HERE RATHER THAN STORED: the assertion
// that matters is "the returned image is the RAM array and not the 4-byte
// port prefix". A stored copy of the expected bytes proves the two files
// agree; recomputing the generator's closed-form pattern proves the slice
// landed on the right offset. The pattern's first four bytes (13, 20, 27, 34)
// are deliberately different from the port prefix (231, 47, 0, 0), which is
// what makes a wrong offset observable instead of merely possible.
//
// Never add this file to `test-gate.mjs`'s MANUAL_ONLY_TESTS: it needs no
// external binary, no emulator and no network, so it belongs in the
// auto-discovered automated set.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import {
  listSnapshotModules,
  sliceC64Mem,
  VsfSliceError,
  FIRST_MODULE_OFFSET,
  MODULE_HEADER_LEN,
  MODULE_NAME_LEN,
  MIN_C64MEM_BODY_LEN,
  V01_C64MEM_BODY_LEN,
  RAM_OFFSET,
  RAM_SIZE,
} from "./vsf-slice.ts";
import { codeOnly } from "./shipped-modules.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const MODULE_PATH = join(HERE, "vsf-slice.ts");

/** Reads one committed fixture as bytes. Takes the bare fixture name so no
 * test spells the directory or the extension, and a fixture rename cannot
 * half-land. */
function fixture(name: string): Uint8Array {
  return readFileSync(join(HERE, "fixtures", "vsf", `${name}.vsf`));
}

/** The generator's closed-form RAM pattern, recomputed rather than stored.
 * `fixtures/vsf/make-fixtures.mjs` builds the minor-1 fixture with
 * `(7, 13)` and the minor-0 fixture with `(11, 5)`. */
function ramPattern(mul: number, add: number): Uint8Array {
  const ram = new Uint8Array(RAM_SIZE);
  for (let i = 0; i < ram.length; i++) ram[i] = (i * mul + add) & 0xff;
  return ram;
}

/** The measured port prefix, which the slice must NOT return. */
const PORT_PREFIX = [231, 47, 0, 0];

// ---------------------------------------------------------------------------
// The constants, asserted numerically. The module writes each one as
// arithmetic over named constants precisely so the derivation is checkable --
// which is only worth anything if something checks the result.
// ---------------------------------------------------------------------------

test("FIRST_MODULE_OFFSET is 58 -- the second magic block is accounted for", () => {
  // 19 (magic) + 2 (snapshot major/minor) + 16 (machine name) + 13 (version
  // magic) + 4 (VICE version bytes) + 4 (SVN dword). The stale prototype
  // value 37 omits the last three terms and lands inside the version magic.
  assert.equal(FIRST_MODULE_OFFSET, 58);
  assert.notEqual(FIRST_MODULE_OFFSET, 37);
});

test("MIN_C64MEM_BODY_LEN is 65543 and V01_C64MEM_BODY_LEN is 65555, and neither is 4 + 65536", () => {
  assert.equal(MIN_C64MEM_BODY_LEN, 65543);
  assert.equal(V01_C64MEM_BODY_LEN, 65555);
  // The falsified assertion this module exists not to carry: `4 + 65536` is
  // 65540, which is below the real minimum and above nothing, so a slicer
  // asserting equality against it refuses every real snapshot.
  assert.notEqual(MIN_C64MEM_BODY_LEN, RAM_OFFSET + RAM_SIZE);
  assert.notEqual(V01_C64MEM_BODY_LEN, RAM_OFFSET + RAM_SIZE);
});

test("MODULE_HEADER_LEN is 22 and the size field sits at header offset 18", () => {
  assert.equal(MODULE_HEADER_LEN, 22);
  // Asserted through the walk rather than by re-reading the constant: the
  // fixture's MAINCPU module declares size 30, which is only readable as 30
  // if the u32LE is taken from offset 18.
  const modules = listSnapshotModules(fixture("wellformed-minor1"));
  assert.equal(modules[0].size, 30);
  assert.equal(modules[0].bodyLength, 30 - MODULE_HEADER_LEN);
});

// ---------------------------------------------------------------------------
// The strict walk.
// ---------------------------------------------------------------------------

test("listSnapshotModules: returns the well-formed fixture's modules in file order", () => {
  const modules = listSnapshotModules(fixture("wellformed-minor1"));
  assert.deepEqual(
    modules.map((m) => [m.name, m.major, m.minor, m.offset, m.size, m.bodyLength]),
    [
      ["MAINCPU", 1, 4, 58, 30, 8],
      ["C64MEM", 0, 1, 88, 65577, 65555],
      ["GLUE", 1, 0, 65665, 25, 3],
    ],
  );
});

test("listSnapshotModules: the walk ends at EXACTLY the file length", () => {
  const bytes = fixture("wellformed-minor1");
  const modules = listSnapshotModules(bytes);
  const last = modules[modules.length - 1];
  // Stated as the equality rather than left implicit in "it did not throw":
  // this is the cheapest whole-file integrity check the format allows, and it
  // is what would catch a future VICE adding a third magic block loudly.
  assert.equal(last.offset + last.size, bytes.length);
  assert.equal(bytes.length, 65690);
});

test("listSnapshotModules: every module's declared extent lies inside the file", () => {
  const bytes = fixture("wellformed-minor1");
  for (const m of listSnapshotModules(bytes)) {
    assert.ok(m.size >= MODULE_HEADER_LEN, `${m.name} size ${m.size} is below the header length`);
    assert.ok(m.offset + m.size <= bytes.length, `${m.name} runs past the end of the file`);
    assert.equal(m.bodyOffset, m.offset + MODULE_HEADER_LEN);
    assert.equal(m.bodyLength, m.size - MODULE_HEADER_LEN);
  }
});

// ---------------------------------------------------------------------------
// The end-to-end slice.
// ---------------------------------------------------------------------------

test("sliceC64Mem: a well-formed minor-1 snapshot yields exactly 65536 bytes of RAM", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  assert.equal(slice.ram.length, RAM_SIZE);
  assert.deepEqual(Buffer.from(slice.ram), Buffer.from(ramPattern(7, 13)));
});

test("sliceC64Mem: the returned image is the RAM ARRAY, not the 4-byte port prefix", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  assert.deepEqual([...slice.ram.slice(0, 4)], [13, 20, 27, 34]);
  assert.notDeepEqual([...slice.ram.slice(0, 4)], PORT_PREFIX);
});

test("sliceC64Mem: dataOut/dataRead/dirRead come from the 3-byte SUFFIX after the RAM array", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  // The measured suffix, which is the CPU view: dir_read 47 is what the CPU
  // sees at $0000 and data_read 55 at $0001. The prefix's 231 is neither.
  assert.equal(slice.dataOut, 39);
  assert.equal(slice.dataRead, 55);
  assert.equal(slice.dirRead, 47);
  assert.notEqual(slice.dirRead, PORT_PREFIX[0]);
});

test("sliceC64Mem: reports snapshotMinor 1 and bodyLength 65555 for the minor-1 fixture", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  assert.equal(slice.snapshotMinor, 1);
  assert.equal(slice.bodyLength, V01_C64MEM_BODY_LEN);
  assert.equal(slice.bodyLength, 65555);
});

test("sliceC64Mem: the returned image is a COPY -- writing it does not touch the snapshot bytes", () => {
  const bytes = fixture("wellformed-minor1");
  const before = bytes[110 + RAM_OFFSET];
  const slice = sliceC64Mem(bytes);
  slice.ram[0] = (slice.ram[0] + 1) & 0xff;
  assert.equal(bytes[110 + RAM_OFFSET], before);
});

test("VsfSliceError is the module's own named error type", () => {
  // Asserted here so the refusal cases can match on the type rather than on
  // `Error`, which every programming fault also satisfies.
  const err = new VsfSliceError("scratch");
  assert.equal(err.name, "VsfSliceError");
  assert.ok(err instanceof Error);
});

// ---------------------------------------------------------------------------
// Structural SUPPLEMENT: the module is pure -- bytes in, values out.
//
// `codeOnly()` is imported from `shipped-modules.ts`, the single home of the
// full comment-and-string-literal stripper. The import-specifier test needs
// the literal bodies (a specifier IS a string) so it passes `true`; the
// forbidden-call test keeps the default, so a module name mentioned in a
// comment or a message string can never satisfy it.
// ---------------------------------------------------------------------------

/** The exact marker `vsf-slice.ts` uses to separate its pure library from its
 * process entry point. Split on the RAW source, before `codeOnly()` strips
 * comments -- the marker lives in a comment, so a stripped split finds
 * nothing and would silently scan the whole file (or nothing at all). */
const CLI_MARKER = "CLI_REGION_BEGIN";

/** The library half of `vsf-slice.ts`: everything before the CLI marker. This
 * is the region every IMPORTER of the module gets, and the region the purity
 * claim in the module's header is about. Throws rather than returning the
 * whole file if the marker has gone, because a scan that silently widened to
 * include the CLI region would then fail for a reason that looks unrelated,
 * and a scan that silently narrowed to nothing would pass by finding
 * nothing. */
function libraryRegion(): string {
  const src = readFileSync(MODULE_PATH, "utf8");
  const parts = src.split(CLI_MARKER);
  assert.equal(
    parts.length,
    2,
    `vsf-slice.ts must contain the marker ${CLI_MARKER} exactly once -- found ${parts.length - 1} occurrence(s)`,
  );
  return parts[0];
}

test("vsf-slice.ts imports nothing from this repo -- only node: builtins, and only in the CLI region", () => {
  const specifiersIn = (code: string): string[] =>
    [...code.matchAll(/^\s*import\s[^;]*?from\s+"([^"]*)"/gm)].map((m) => m[1]);

  // The whole file: nothing from this repo, by either shape a specifier can
  // take. This is the assertion that keeps the closed five-member host-path
  // consumer set unchanged -- structurally, not by promise.
  const whole = specifiersIn(codeOnly(readFileSync(MODULE_PATH, "utf8"), true));
  assert.deepEqual(whole, ["node:fs", "node:crypto", "node:url", "node:path"]);
  for (const specifier of whole) {
    assert.ok(specifier.startsWith("node:"), `${specifier} is not a node: builtin`);
    assert.ok(!specifier.startsWith("."), `${specifier} is a relative in-repo import`);
    assert.ok(!specifier.startsWith("@henols/"), `${specifier} is an in-repo package import`);
  }

  // The library region imports NOTHING, which is what makes it usable from
  // any context without dragging `node:fs` in behind it.
  assert.deepEqual(specifiersIn(codeOnly(libraryRegion(), true)), []);
});

test("vsf-slice.ts's LIBRARY region performs no filesystem, subprocess or network I/O", () => {
  // Scoped to the library region because the CLI entry point below the marker
  // does exactly the file I/O the library refuses to do -- that is the point
  // of the split, and it is why the scope is derived from a marker in the
  // source rather than from a line number here.
  const code = codeOnly(libraryRegion());
  for (const forbidden of [
    /\b(readFile|readFileSync|writeFile|writeFileSync|appendFileSync|openSync|createReadStream|createWriteStream)\s*\(/,
    /\b(spawn|spawnSync|exec|execSync|execFile|execFileSync|fork)\s*\(/,
    /\b(fetch|request|connect|createConnection|createServer)\s*\(/,
    /\bimport\s*\(/,
    /\bprocess\s*\./,
  ]) {
    assert.equal(
      forbidden.test(code),
      false,
      `vsf-slice.ts's library region must not contain ${forbidden}`,
    );
  }
});

test("the CLI entry point is guarded: main() is only reachable behind the entry-point check", () => {
  const code = codeOnly(readFileSync(MODULE_PATH, "utf8"));
  // Exactly one `process.exit(` call site in the whole module, and it sits
  // inside the guard. Asserted on the source because the alternative -- an
  // unguarded top-level call -- would run main() on every import and could
  // not be observed by importing the module (the runner would be gone).
  const exits = [...code.matchAll(/process\.exit\s*\(/g)];
  assert.equal(exits.length, 1, "vsf-slice.ts must have exactly one process.exit() call site");
  assert.match(code, /if \(isProcessEntryPoint\(\)\) \{\s*process\.exit\(main\(process\.argv\.slice\(2\)\)\);\s*\}/);
  // The guard is path arithmetic, never a filesystem call, so the check
  // itself does no I/O on import.
  assert.match(code, /resolve\(entry\) === fileURLToPath\(import\.meta\.url\)/);
  assert.equal(/realpathSync/.test(code), false, "the entry-point guard must not touch the filesystem");
});

test("importing vsf-slice.ts runs nothing: a fresh process that only imports it exits 0 and prints nothing", () => {
  // The behavioural half of the guard assertion above. Run in a CHILD
  // process: if the module ran main() on import, this test file's own import
  // of it would already have terminated the runner, so the failure would look
  // like a crash rather than a failed assertion.
  const r = spawnSync(process.execPath, ["--input-type=module", "-e", 'await import("./vsf-slice.ts");'], {
    cwd: HERE,
    encoding: "utf8",
    timeout: 30000,
  });
  assert.equal(r.status, 0, `importing the module failed: ${r.stderr}`);
  assert.equal(r.stdout, "", `importing the module printed to stdout: ${r.stdout}`);
});

test("the CLI writes exactly 65536 bytes for a well-formed snapshot and exits 0", () => {
  const out = join(mkdtempSync(join(tmpdir(), "vsf-slice-cli-")), "image.bin");
  const r = spawnSync(
    process.execPath,
    [MODULE_PATH, "slice", join(HERE, "fixtures", "vsf", "wellformed-minor1.vsf"), "--out", out],
    { encoding: "utf8", timeout: 30000 },
  );
  assert.equal(r.status, 0, r.stderr);
  assert.equal(readFileSync(out).length, RAM_SIZE);
  assert.match(r.stdout, /C64MEM minor 1, body 65555 bytes/);
  assert.match(r.stdout, /data_out=39 data_read=55 dir_read=47/);
});

test("the CLI exits non-zero on a malformed snapshot and prints the module's OWN message, unmodified", () => {
  const out = join(mkdtempSync(join(tmpdir(), "vsf-slice-cli-")), "image.bin");
  const r = spawnSync(
    process.execPath,
    [MODULE_PATH, "slice", join(HERE, "fixtures", "vsf", "malformed-header.vsf"), "--out", out],
    { encoding: "utf8", timeout: 30000 },
  );
  assert.notEqual(r.status, 0, "a malformed snapshot must not exit 0");
  // Verbatim, with nothing prefixed: the message starts at the library
  // function's own name.
  assert.match(r.stderr.trim(), /^listSnapshotModules: malformed module header at offset 88/);
  assert.match(r.stderr, /[Rr]efusing rather than rescanning/);
  // And no image was written at all -- not even a short one.
  assert.equal(existsSync(out), false, "a refused slice must leave no output file behind");
});

test("no exported function takes a filesystem path -- both take a byte array", () => {
  // Read from the source rather than asserted in prose: the signature is the
  // property that keeps path traversal out of this module's threat surface,
  // and a header sentence cannot notice when an edit falsifies it.
  const code = codeOnly(readFileSync(MODULE_PATH, "utf8"));
  const signatures = [...code.matchAll(/export function (\w+)\(([^)]*)\)/g)].map((m) => [
    m[1],
    m[2].trim(),
  ]);
  assert.deepEqual(signatures, [
    ["listSnapshotModules", "bytes: Uint8Array"],
    ["sliceC64Mem", "bytes: Uint8Array"],
  ]);
});

// ---------------------------------------------------------------------------
// The refusal cases. Each one is a first-class deliverable with its own
// fixture or its own in-test construction, and each asserts the MESSAGE
// content rather than merely that something threw -- a bare `assert.throws`
// passes for a typo in the function name.
//
// The specific historical failure this whole section closes: a slicer that
// returns a plausible 65536 bytes of garbage rather than refusing. That is
// the transcription defect (one 32 KB write truncated mid-payload, one 8 KB
// write dropping ten characters localised to `$7871`) reproduced with more
// steps, and every number measured downstream would inherit it silently.
// ---------------------------------------------------------------------------

/** Rewrites a module header's 16-byte NUL-padded name IN A COPY, so a case
 * built from a fixture cannot drift from that fixture and cannot mutate it.
 * `new Uint8Array(bytes)` copies for both `Buffer` and `Uint8Array` input --
 * unlike `bytes.slice()`, whose `Buffer` override is a view. */
function withModuleNameAt(bytes: Uint8Array, offset: number, name: string): Uint8Array {
  assert.ok(name.length <= MODULE_NAME_LEN, "test helper misuse: name wider than the name field");
  const copy = new Uint8Array(bytes);
  for (let i = 0; i < MODULE_NAME_LEN; i++) {
    copy[offset + i] = i < name.length ? name.charCodeAt(i) : 0;
  }
  return copy;
}

/** The two module-header offsets the fixtures put MAINCPU and C64MEM at.
 * Asserted against the walk in the Task-1 tests above, so these are read
 * values rather than magic numbers. */
const MAINCPU_HEADER_OFFSET = 58;
const C64MEM_HEADER_OFFSET = 88;

test("malformed module header: refuses at the offset, naming it, and says it did not rescan", () => {
  assert.throws(
    () => sliceC64Mem(fixture("malformed-header")),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /offset 88/);
      assert.match(err.message, /size=21/);
      assert.match(err.message, /[Rr]efusing rather than rescanning/);
      return true;
    },
  );
});

test("the refusal DISCRIMINATES: the well-formed fixture in the same test does not throw", () => {
  // Without this half, a slicer that threw unconditionally would pass the
  // test above. The positive control is what makes the refusal a refusal
  // rather than a blanket failure.
  assert.throws(() => sliceC64Mem(fixture("malformed-header")), VsfSliceError);
  assert.doesNotThrow(() => sliceC64Mem(fixture("wellformed-minor1")));
});

test("malformed module header: an implementation that rescanned would reach C64MEM -- it must not", () => {
  // The positive control stated as the property it protects. The malformed
  // fixture's bad header IS a `C64MEM` header (name bytes and all); only its
  // size field is impossible. An `off++` rescan fallback would step past it,
  // find no further module, and either return garbage or fail elsewhere. So
  // the observable requirement is that the failure names the HEADER, at its
  // offset -- not the body length, and not a missing module.
  const modules = listSnapshotModules(fixture("wellformed-minor1")).map((m) => m.name);
  assert.deepEqual(modules, ["MAINCPU", "C64MEM", "GLUE"], "fixture drift: the walk shape changed");
  assert.throws(() => listSnapshotModules(fixture("malformed-header")), /malformed module header/);
});

test("short C64MEM body: refuses naming both the observed 65542 and the minimum 65543", () => {
  assert.throws(
    () => sliceC64Mem(fixture("short-c64mem")),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /65542/);
      assert.match(err.message, /65543/);
      assert.match(err.message, /[Rr]efusing a short read/);
      return true;
    },
  );
});

test("the body-length BOUNDARY, as a boundary: 65543 is accepted and 65542 is refused", () => {
  // Both calls in one test so the boundary is visible as a boundary rather
  // than as two unrelated results in two places.
  const accepted = sliceC64Mem(fixture("wellformed-minor0"));
  assert.equal(accepted.bodyLength, MIN_C64MEM_BODY_LEN);
  assert.equal(accepted.bodyLength, 65543);
  assert.equal(accepted.ram.length, RAM_SIZE);
  assert.throws(() => sliceC64Mem(fixture("short-c64mem")), /65542/);
});

test("snapshot minor 0: 65536 RAM bytes, snapshotMinor 0, bodyLength 65543, suffix bytes present", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor0"));
  assert.equal(slice.ram.length, RAM_SIZE);
  assert.deepEqual(Buffer.from(slice.ram), Buffer.from(ramPattern(11, 5)));
  assert.equal(slice.snapshotMinor, 0);
  assert.equal(slice.bodyLength, 65543);
  // The three port read-back bytes EXIST at minor 0 -- only the four
  // DWORD/state fields after them are absent -- so dataRead and dirRead are
  // available on this branch too and are not defaulted to zero.
  assert.equal(slice.dataOut, 39);
  assert.equal(slice.dataRead, 55);
  assert.equal(slice.dirRead, 47);
});

test("no C64MEM module: refuses listing the module names that WERE found", () => {
  // Built by rewriting the fixture's own C64MEM name bytes, so this case
  // cannot drift from the fixture it is derived from.
  const renamed = withModuleNameAt(fixture("wellformed-minor1"), C64MEM_HEADER_OFFSET, "C64RAM");
  assert.throws(
    () => sliceC64Mem(renamed),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /no module named "C64MEM" found/);
      assert.match(err.message, /MAINCPU/);
      assert.match(err.message, /C64RAM/);
      assert.match(err.message, /GLUE/);
      return true;
    },
  );
});

test("a name that merely CONTAINS C64MEM does not match -- C64MEMHACKS is a real adjacent module", () => {
  const renamed = withModuleNameAt(
    fixture("wellformed-minor1"),
    C64MEM_HEADER_OFFSET,
    "C64MEMHACKS",
  );
  assert.throws(() => sliceC64Mem(renamed), /no module named "C64MEM" found/);
  // And the walk itself still reads that name back byte-exactly, so the
  // failure above is a non-match rather than a decode error.
  assert.equal(listSnapshotModules(renamed)[1].name, "C64MEMHACKS");
});

test("two C64MEM modules: refuses naming the count and both offsets, never first-wins", () => {
  const duplicated = withModuleNameAt(
    fixture("wellformed-minor1"),
    MAINCPU_HEADER_OFFSET,
    "C64MEM",
  );
  let result: unknown;
  assert.throws(
    () => {
      result = sliceC64Mem(duplicated);
    },
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /duplicated/);
      assert.match(err.message, /2 modules/);
      assert.match(err.message, /58/);
      assert.match(err.message, /88/);
      return true;
    },
  );
  // The first-wins failure stated as an observation: the genuine 65555-byte
  // C64MEM sits second, and an implementation taking `matches[0]` would have
  // returned the 8-byte MAINCPU body's slice -- or a short read of it.
  assert.equal(result, undefined, "a duplicated module name must never return either module's bytes");
});

test("a zero-byte input is refused by name, never as a short buffer", () => {
  assert.throws(
    () => sliceC64Mem(new Uint8Array(0)),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /is 0 byte\(s\)/);
      assert.match(err.message, /at least 80/);
      return true;
    },
  );
});

test("an input one byte short of a file header plus one module header is refused by name", () => {
  const short = new Uint8Array(FIRST_MODULE_OFFSET + MODULE_HEADER_LEN - 1);
  assert.equal(short.length, 79);
  assert.throws(
    () => sliceC64Mem(short),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /is 79 byte\(s\)/);
      assert.match(err.message, /at least 80/);
      return true;
    },
  );
  // And exactly one more byte gets PAST the length gate, so the gate is on
  // the boundary rather than somewhere near it. It then fails on the magic,
  // which is the next check and a different message.
  assert.throws(() => sliceC64Mem(new Uint8Array(80)), /snapshot magic/);
});

test("a file long enough but without the snapshot magic is refused by name", () => {
  const bogus = new Uint8Array(200);
  bogus.fill(0x41);
  assert.throws(
    () => sliceC64Mem(bogus),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /does not begin with the 19-byte VICE snapshot magic/);
      return true;
    },
  );
});

test("a walk that does not end exactly at the file length is refused, naming both numbers", () => {
  // Append one trailing byte to a well-formed fixture: every module still
  // parses cleanly, so this is the ONLY check that catches it -- which is
  // exactly the shape a future VICE adding a third magic block would have.
  const original = fixture("wellformed-minor1");
  const padded = new Uint8Array(original.length + 1);
  padded.set(original);
  assert.throws(
    () => listSnapshotModules(padded),
    (err: Error) => {
      assert.ok(err instanceof VsfSliceError, `expected a VsfSliceError, got ${err.name}`);
      assert.match(err.message, /ended at offset 65690/);
      assert.match(err.message, /65691 byte\(s\)/);
      assert.match(err.message, /3 module\(s\) parsed cleanly/);
      return true;
    },
  );
});

// ---------------------------------------------------------------------------
// The fixtures' own provenance. A synthetic fixture that does not say so is
// worse than no fixture: every number measured on this substrate rests on
// knowing which bytes were captured and which were constructed.
// ---------------------------------------------------------------------------

test("every .vsf fixture has a sidecar declaring itself synthetic and naming its generator", () => {
  const names = ["wellformed-minor1", "wellformed-minor0", "malformed-header", "short-c64mem"];
  for (const name of names) {
    const sidecar = JSON.parse(
      readFileSync(join(HERE, "fixtures", "vsf", `${name}.json`), "utf8"),
    ) as Record<string, unknown>;
    for (const key of ["capturedFrom", "viceVersion", "capturedAt", "command", "synthetic"]) {
      assert.ok(key in sidecar, `${name}.json is missing the required provenance key ${key}`);
    }
    assert.equal(sidecar.synthetic, true, `${name}.json must declare itself synthetic`);
    assert.match(String(sidecar.command), /make-fixtures\.mjs/);
    assert.equal(sidecar.fileBytes, fixture(name).length, `${name}.json's fileBytes is stale`);
  }
});

test("vsf-slice.ts is in package.json files[] and no fixtures entry is", () => {
  // Two mechanical reasons the module must be listed, both stated in its own
  // header: the skill-side route resolves it inside the published tarball,
  // and `shippedTsModules()` -- which every structural guard scans -- is
  // derived from `files[]`, so an unlisted module is outside the scanned set.
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8")) as { files: string[] };
  assert.ok(pkg.files.includes("vsf-slice.ts"), "vsf-slice.ts is missing from files[]");
  assert.deepEqual(
    pkg.files.filter((f) => /fixtures/.test(f)),
    [],
    "fixtures are test-support and must never ship: the package-contents validator fails a pack that leaks one",
  );
});
