// vsf-slice.test.ts
//
// The committed regression for `vsf-slice.ts`: the end-to-end slice of a
// well-formed snapshot, plus a structural check that the module really is the
// pure, I/O-free, imports-nothing thing its header claims.
//
// WHY THE FIXTURES ARE SYNTHETIC AND SAY SO: no corpus byte, snapshot or
// capture image is ever committed to this repository. The four fixtures under
// `fixtures/vsf/` are generated by `fixtures/vsf/make-fixtures.mjs`, each
// carries a `"synthetic": true` provenance sidecar naming that generator, and
// their LAYOUT is modelled byte-for-byte on the measured layout of a genuine
// VICE 3.9 snapshot. A synthetic fixture claiming to be a capture would be
// worse than no fixture at all.
//
// WHY THE RAM PATTERN IS RECOMPUTED HERE RATHER THAN STORED: the assertion
// that matters is "the returned image is the RAM array and not the 4-byte
// port prefix". A stored copy of the expected bytes proves the two files
// agree; recomputing the generator's closed-form pattern proves the slice
// landed on the right offset. The pattern's first four bytes (13, 20, 27, 34)
// are deliberately different from the port prefix (231, 47, 0, 0), which is
// what makes a wrong offset observable instead of merely possible.
//
// Never add this file to `test-gate.mjs`'s MANUAL_ONLY_TESTS: it needs no
// external binary, no emulator and no network, so it belongs in the
// auto-discovered automated set.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import {
  listSnapshotModules,
  sliceC64Mem,
  VsfSliceError,
  FIRST_MODULE_OFFSET,
  MODULE_HEADER_LEN,
  MIN_C64MEM_BODY_LEN,
  V01_C64MEM_BODY_LEN,
  RAM_OFFSET,
  RAM_SIZE,
} from "./vsf-slice.ts";
import { codeOnly } from "./shipped-modules.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const MODULE_PATH = join(HERE, "vsf-slice.ts");

/** Reads one committed fixture as bytes. Takes the bare fixture name so no
 * test spells the directory or the extension, and a fixture rename cannot
 * half-land. */
function fixture(name: string): Uint8Array {
  return readFileSync(join(HERE, "fixtures", "vsf", `${name}.vsf`));
}

/** The generator's closed-form RAM pattern, recomputed rather than stored.
 * `fixtures/vsf/make-fixtures.mjs` builds the minor-1 fixture with
 * `(7, 13)` and the minor-0 fixture with `(11, 5)`. */
function ramPattern(mul: number, add: number): Uint8Array {
  const ram = new Uint8Array(RAM_SIZE);
  for (let i = 0; i < ram.length; i++) ram[i] = (i * mul + add) & 0xff;
  return ram;
}

/** The measured port prefix, which the slice must NOT return. */
const PORT_PREFIX = [231, 47, 0, 0];

// ---------------------------------------------------------------------------
// The constants, asserted numerically. The module writes each one as
// arithmetic over named constants precisely so the derivation is checkable --
// which is only worth anything if something checks the result.
// ---------------------------------------------------------------------------

test("FIRST_MODULE_OFFSET is 58 -- the second magic block is accounted for", () => {
  // 19 (magic) + 2 (snapshot major/minor) + 16 (machine name) + 13 (version
  // magic) + 4 (VICE version bytes) + 4 (SVN dword). The stale prototype
  // value 37 omits the last three terms and lands inside the version magic.
  assert.equal(FIRST_MODULE_OFFSET, 58);
  assert.notEqual(FIRST_MODULE_OFFSET, 37);
});

test("MIN_C64MEM_BODY_LEN is 65543 and V01_C64MEM_BODY_LEN is 65555, and neither is 4 + 65536", () => {
  assert.equal(MIN_C64MEM_BODY_LEN, 65543);
  assert.equal(V01_C64MEM_BODY_LEN, 65555);
  // The falsified assertion this module exists not to carry: `4 + 65536` is
  // 65540, which is below the real minimum and above nothing, so a slicer
  // asserting equality against it refuses every real snapshot.
  assert.notEqual(MIN_C64MEM_BODY_LEN, RAM_OFFSET + RAM_SIZE);
  assert.notEqual(V01_C64MEM_BODY_LEN, RAM_OFFSET + RAM_SIZE);
});

test("MODULE_HEADER_LEN is 22 and the size field sits at header offset 18", () => {
  assert.equal(MODULE_HEADER_LEN, 22);
  // Asserted through the walk rather than by re-reading the constant: the
  // fixture's MAINCPU module declares size 30, which is only readable as 30
  // if the u32LE is taken from offset 18.
  const modules = listSnapshotModules(fixture("wellformed-minor1"));
  assert.equal(modules[0].size, 30);
  assert.equal(modules[0].bodyLength, 30 - MODULE_HEADER_LEN);
});

// ---------------------------------------------------------------------------
// The strict walk.
// ---------------------------------------------------------------------------

test("listSnapshotModules: returns the well-formed fixture's modules in file order", () => {
  const modules = listSnapshotModules(fixture("wellformed-minor1"));
  assert.deepEqual(
    modules.map((m) => [m.name, m.major, m.minor, m.offset, m.size, m.bodyLength]),
    [
      ["MAINCPU", 1, 4, 58, 30, 8],
      ["C64MEM", 0, 1, 88, 65577, 65555],
      ["GLUE", 1, 0, 65665, 25, 3],
    ],
  );
});

test("listSnapshotModules: the walk ends at EXACTLY the file length", () => {
  const bytes = fixture("wellformed-minor1");
  const modules = listSnapshotModules(bytes);
  const last = modules[modules.length - 1];
  // Stated as the equality rather than left implicit in "it did not throw":
  // this is the cheapest whole-file integrity check the format allows, and it
  // is what would catch a future VICE adding a third magic block loudly.
  assert.equal(last.offset + last.size, bytes.length);
  assert.equal(bytes.length, 65690);
});

test("listSnapshotModules: every module's declared extent lies inside the file", () => {
  const bytes = fixture("wellformed-minor1");
  for (const m of listSnapshotModules(bytes)) {
    assert.ok(m.size >= MODULE_HEADER_LEN, `${m.name} size ${m.size} is below the header length`);
    assert.ok(m.offset + m.size <= bytes.length, `${m.name} runs past the end of the file`);
    assert.equal(m.bodyOffset, m.offset + MODULE_HEADER_LEN);
    assert.equal(m.bodyLength, m.size - MODULE_HEADER_LEN);
  }
});

// ---------------------------------------------------------------------------
// The end-to-end slice.
// ---------------------------------------------------------------------------

test("sliceC64Mem: a well-formed minor-1 snapshot yields exactly 65536 bytes of RAM", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  assert.equal(slice.ram.length, RAM_SIZE);
  assert.deepEqual(Buffer.from(slice.ram), Buffer.from(ramPattern(7, 13)));
});

test("sliceC64Mem: the returned image is the RAM ARRAY, not the 4-byte port prefix", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  assert.deepEqual([...slice.ram.slice(0, 4)], [13, 20, 27, 34]);
  assert.notDeepEqual([...slice.ram.slice(0, 4)], PORT_PREFIX);
});

test("sliceC64Mem: dataOut/dataRead/dirRead come from the 3-byte SUFFIX after the RAM array", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  // The measured suffix, which is the CPU view: dir_read 47 is what the CPU
  // sees at $0000 and data_read 55 at $0001. The prefix's 231 is neither.
  assert.equal(slice.dataOut, 39);
  assert.equal(slice.dataRead, 55);
  assert.equal(slice.dirRead, 47);
  assert.notEqual(slice.dirRead, PORT_PREFIX[0]);
});

test("sliceC64Mem: reports snapshotMinor 1 and bodyLength 65555 for the minor-1 fixture", () => {
  const slice = sliceC64Mem(fixture("wellformed-minor1"));
  assert.equal(slice.snapshotMinor, 1);
  assert.equal(slice.bodyLength, V01_C64MEM_BODY_LEN);
  assert.equal(slice.bodyLength, 65555);
});

test("sliceC64Mem: the returned image is a COPY -- writing it does not touch the snapshot bytes", () => {
  const bytes = fixture("wellformed-minor1");
  const before = bytes[110 + RAM_OFFSET];
  const slice = sliceC64Mem(bytes);
  slice.ram[0] = (slice.ram[0] + 1) & 0xff;
  assert.equal(bytes[110 + RAM_OFFSET], before);
});

test("VsfSliceError is the module's own named error type", () => {
  // Asserted here so the refusal cases can match on the type rather than on
  // `Error`, which every programming fault also satisfies.
  const err = new VsfSliceError("scratch");
  assert.equal(err.name, "VsfSliceError");
  assert.ok(err instanceof Error);
});

// ---------------------------------------------------------------------------
// Structural SUPPLEMENT: the module is pure -- bytes in, values out.
//
// `codeOnly()` is imported from `shipped-modules.ts`, the single home of the
// full comment-and-string-literal stripper. The import-specifier test needs
// the literal bodies (a specifier IS a string) so it passes `true`; the
// forbidden-call test keeps the default, so a module name mentioned in a
// comment or a message string can never satisfy it.
// ---------------------------------------------------------------------------

test("vsf-slice.ts imports nothing at all -- and in particular nothing from this repo", () => {
  const code = codeOnly(readFileSync(MODULE_PATH, "utf8"), true);
  const specifiers = [...code.matchAll(/^\s*import\s[^;]*?from\s+"([^"]*)"/gm)].map((m) => m[1]);
  assert.deepEqual(specifiers, []);
});

test("vsf-slice.ts performs no filesystem, subprocess or network I/O", () => {
  const code = codeOnly(readFileSync(MODULE_PATH, "utf8"));
  for (const forbidden of [
    /\b(readFile|readFileSync|writeFile|writeFileSync|appendFileSync|openSync|createReadStream|createWriteStream)\s*\(/,
    /\b(spawn|spawnSync|exec|execSync|execFile|execFileSync|fork)\s*\(/,
    /\b(fetch|request|connect|createConnection|createServer)\s*\(/,
    /\bimport\s*\(/,
    /\bprocess\s*\./,
  ]) {
    assert.equal(forbidden.test(code), false, `vsf-slice.ts must not contain ${forbidden}`);
  }
});

test("no exported function takes a filesystem path -- both take a byte array", () => {
  // Read from the source rather than asserted in prose: the signature is the
  // property that keeps path traversal out of this module's threat surface,
  // and a header sentence cannot notice when an edit falsifies it.
  const code = codeOnly(readFileSync(MODULE_PATH, "utf8"));
  const signatures = [...code.matchAll(/export function (\w+)\(([^)]*)\)/g)].map((m) => [
    m[1],
    m[2].trim(),
  ]);
  assert.deepEqual(signatures, [
    ["listSnapshotModules", "bytes: Uint8Array"],
    ["sliceC64Mem", "bytes: Uint8Array"],
  ]);
});
