;=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
;
; Auto-generated by Regenerator 2000 v0.9.20
; https://github.com/ricardoquesada/regenerator2000
;
; Assemble with:
;   acme --cpu 6510 --format cbm -o r2000.prg r2000.asm
;
;=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
; EXTERNAL LABELS
;   zpf_ = Zero Page Field
;   zpa_ = Zero Page Absolute Address
;   zpp_ = Zero Page Pointer
;   f_   = Field
;   a_   = Absolute Address
;   e_   = External Jump
;   L_   = Other / User-defined

zpp_00 = $00                             ; x-ref: $0902
zpp_02 = $02                             ; x-ref: $08c0
zpp_04 = $04                             ; x-ref: $08c2
zpa_06 = $06                             ; x-ref: $08c4
zpf_08 = $08                             ; x-ref: $08b9, $08bd, $08c6
zpp_10 = $10                             ; x-ref: $08ff
zpp_14 = $14                             ; x-ref: $08d2
zpf_16 = $16                             ; x-ref: $08d4
zpf_18 = $18                             ; x-ref: $08d6
zpp_20 = $20                             ; x-ref: $0904
f_0045 = $45                             ; x-ref: $086d
zpa_4C = $4c                             ; x-ref: $0864
e_004F = $4f                             ; x-ref: $0866
zpp_95 = $95                             ; x-ref: $08b1
zpf_9A = $9a                             ; x-ref: $08ac
zpa_FB = $fb                             ; x-ref: $0827, $082e
zpa_FC = $fc                             ; x-ref: $082c
zpa_FD = $fd                             ; x-ref: $0872, $0879, $0885, $0887, $088e
zpa_FE = $fe                             ; x-ref: $0875, $0889
f_01FF = $01ff                           ; x-ref: $0907
a_0400 = $0400                           ; x-ref: $08a7
a_0F0E = $0f0e                           ; x-ref: $08cc
f_1B1A = $1b1a                           ; x-ref: $08d8
f_1F1E = $1f1e                           ; x-ref: $08dc
KERNAL_CHROUT = $ffd2                    ; $FFD2 - output character ; x-ref: $087d

* = $0801
                    anc #$08
                    asl 
                    brk 
                    !byte $9e            ; Invalid or partial instruction
                    !byte $32            ; Invalid or partial instruction
f_0808 =*+$01
                    bmi b_083F
                    !byte $34            ; Invalid or partial instruction
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    lda #$00
                    sta $d020            ; Border Color
                    ldx #$00
b_0817              lda f_08BF,x         ; x-ref: $0820
                    sta f_08DF,x
                    inx 
                    cpx #$20
                    bne b_0817
                    ldx #$02
                    lda f_08AB,x
                    sta zpa_FB
                    lda f_08AE,x
                    sta zpa_FC
                    jmp (zpa_FB)
                    ldx #$01
                    lda f_08B4,x
                    pha 
                    lda f_08B1,x
                    pha 
                    rts 
                    ldx #$00
b_083F =*+$01
b_083E              lda f_08FF,x         ; x-ref: $085d
                    beq b_0856
                    lda f_0900,x
                    clc 
                    adc f_0902,x
                    sta f_0900,x
                    lda f_0901,x
                    adc f_0903,x
                    sta f_0901,x
b_0856              txa                  ; x-ref: $0841
                    clc 
                    adc #$05
                    tax 
                    cpx #$19
                    bne b_083E
                    rts 
                    jsr s_0871
                    pha 
                    eor zpa_4C
                    jmp+2 e_004F
                    jsr s_0871
                    !byte $42            ; Invalid or partial instruction
                    eor+2 f_0045,y
                    rts 
s_0871              pla                  ; x-ref: $0860, $0869
                    sta zpa_FD
                    pla 
                    sta zpa_FE
                    ldy #$01
b_0879              lda (zpa_FD),y       ; x-ref: $0881
                    beq b_0883
                    jsr KERNAL_CHROUT    ; $FFD2 - output character
                    iny 
                    bne b_0879
b_0883              tya                  ; x-ref: $087b
                    clc 
                    adc zpa_FD
                    sta zpa_FD
                    lda zpa_FE
                    adc #$00
                    pha 
                    lda zpa_FD
                    pha 
                    rts 
                    inc $d021            ; Background Color 0
                    rts 
                    dec $d021            ; Background Color 0
                    rts 
                    lda #$07
                    sta $d021            ; Background Color 0
                    rts 
                    lda #$aa
                    sta a_08A6
a_08A6 =*+$01
                    lda #$00
                    sta a_0400
                    rts 
f_08AB              !byte $92            ; x-ref: $0824; Invalid or partial instruction
                    stx zpf_9A,y
f_08AE              php                  ; x-ref: $0829
                    php 
                    php 
f_08B1              sta (zpp_95),y       ; x-ref: $0837
f_08B4 =*+$01
                    sta f_0808,y
                    php 
                    !byte $92            ; Invalid or partial instruction
                    php 
                    stx zpf_08,y
                    txs 
                    php 
                    adc (zpf_08),y
f_08BF              brk                  ; x-ref: $0817
                    ora (zpp_02,x)
                    slo (zpp_04,x)
                    ora zpa_06
                    slo zpf_08
                    ora #$0a
                    anc #$0c
                    ora a_0F0E
                    bpl b_08E2
                    !byte $12            ; Invalid or partial instruction
                    slo (zpp_14),y
                    ora zpf_16,x
                    slo zpf_18,x
                    ora f_1B1A,y
                    !byte $1c            ; Invalid or partial instruction
                    ora f_1F1E,x
f_08DF              brk                  ; x-ref: $081a
                    brk 
                    brk 
b_08E2              brk                  ; x-ref: $08cf
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
f_0900 =*+$01
f_08FF              ora (zpp_10,x)       ; x-ref: $083e
f_0901              brk                  ; x-ref: $084d, $0853
f_0903 =*+$01
f_0902              ora (zpp_00,x)       ; x-ref: $0847
                    ora (zpp_20,x)
                    brk 
                    isc f_01FF,x
                    bmi b_090C
b_090C              !byte $02            ; x-ref: $090a; Invalid or partial instruction
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
                    brk 
