// anno-cli-smoke.test.ts -- the shipped `anno` bin, spawned, with its
// default wiring: no injected runner and no broker.
//
// Every other anno CLI test drives `runAnnoCli()` in-process with an injected
// runner. These few prove the default: the bin finds the workspace through
// CLAUDE_PROJECT_DIR, a first write creates .c64-re-tools/annotations.db
// there, and each report writes its result where --out names.
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { closeAnnoDatabase, openAnnoDatabase, soleProjectStore } from "../../src/mcp/vice/anno-store.mts";
import { annoDbPath } from "../../src/mcp/vice/anno-workspace-store.ts";
import { VICE_DIR } from "./paths.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const VICE_PROXY = join(VICE_DIR, "vice-proxy.ts");

let ws: string;
let fresh: string;
let moved: string;

before(async () => {
  ws = mkdtempSync(join(tmpdir(), "anno-cli-smoke-"));
  fresh = mkdtempSync(join(tmpdir(), "anno-cli-smoke-fresh-"));
  moved = mkdtempSync(join(tmpdir(), "anno-cli-smoke-moved-"));
  // lda #$01 / sta $d020 / rts, loaded at $c000.
  writeFileSync(join(ws, "game.prg"), Buffer.from([0x00, 0xc0, 0xa9, 0x01, 0x8d, 0x20, 0xd0, 0x60]));
  writeFileSync(
    join(ws, "sidecar.json"),
    JSON.stringify({
      capturePath: "/tmp/capture.raw",
      captureSha256: "a".repeat(64),
      port01: "$35",
      dd00: "$06",
      vicBank: "0 ($0000-$3FFF)",
      screenRam: "$0400",
      charsetOrBitmap: "$1000 (ROM shadow)",
      mode: "text, multicolor off",
      videoStandard: "PAL",
      liveVectorPair: "$0314/$0315",
      vectorHandler: "$EA31",
    }),
  );
});

after(async () => {
  for (const dir of [ws, fresh, moved]) if (dir !== undefined) rmSync(dir, { recursive: true, force: true });
});

function anno(workspace: string, argv: string[]) {
  return spawnSync(process.execPath, [VICE_PROXY, "anno", ...argv], {
    encoding: "utf8" as const,
    env: { ...process.env, CLAUDE_PROJECT_DIR: workspace, VICE_SKIP_RESOURCE_INSTALL: "1", MASTRA_TELEMETRY_DISABLED: "1" },
    timeout: 30_000,
  });
}

/** The one project a workspace's annotations.db holds. */
function projectIdOf(workspace: string): string {
  const adb = openAnnoDatabase(annoDbPath(workspace), { unconfinedModuleDerivedPath: true });
  try {
    return soleProjectStore(adb).projectId;
  } finally {
    closeAnnoDatabase(adb);
  }
}

test("smoke: the first write through the bin creates the workspace's annotations.db, and export-asm writes the tree at --out", () => {
  const typed = anno(ws, ["call", "anno_set_data_type", "--args", JSON.stringify({ start_address: "$c000", end_address: "$c005", data_type: "code" })]);
  assert.equal(typed.status, 0, typed.stderr);
  assert.ok(existsSync(join(ws, ".c64-re-tools", "annotations.db")), "the first write must create the workspace's annotations.db");
  const labelled = anno(ws, ["call", "anno_set_label_name", "--args", JSON.stringify({ address: "$c000", name: "start" })]);
  assert.equal(labelled.status, 0, labelled.stderr);

  const exported = anno(ws, ["export-asm", join(ws, "game.prg"), "--out", join(ws, "game-src")]);
  assert.equal(exported.status, 0, exported.stderr);
  assert.ok(readdirSync(join(ws, "game-src")).length >= 3, "the tree's files are written at --out");
  assert.match(readFileSync(join(ws, "game-src", "symbols.a"), "utf8"), /^start = \$c000$/m);
});

test("smoke: render-memmap writes the map at --out, and --check then reports it in sync", () => {
  const out = join(ws, "memory-map.md");
  const rendered = anno(ws, ["render-memmap", "--provenance", join(ws, "sidecar.json"), "--out", out]);
  assert.equal(rendered.status, 0, rendered.stderr);
  assert.match(readFileSync(out, "utf8"), /GENERATED by/);
  const checked = anno(ws, ["render-memmap", "--provenance", join(ws, "sidecar.json"), "--out", out, "--check"]);
  assert.equal(checked.status, 0, checked.stderr);
  assert.match(checked.stdout, /in sync/);
});

test("smoke: coverage writes its JSON report at --out, naming the image by the caller's own path", () => {
  const out = join(ws, "coverage.json");
  const covered = anno(ws, ["coverage", join(ws, "game.prg"), "--out", out]);
  assert.equal(covered.status, 0, covered.stderr);
  const report = JSON.parse(readFileSync(out, "utf8")) as { project: { path: string } };
  assert.equal(report.project.path, join(ws, "game.prg"));
});

test("smoke: export-project and import-project move the project into another workspace, and it exports back byte for byte", () => {
  const backup = join(ws, "backup.json");
  const exported = anno(ws, ["export-project", "--out", backup]);
  assert.equal(exported.status, 0, exported.stderr);

  writeFileSync(join(moved, "backup.json"), readFileSync(backup));
  const imported = anno(moved, ["import-project", join(moved, "backup.json")]);
  assert.equal(imported.status, 0, imported.stderr);
  assert.notEqual(projectIdOf(moved), projectIdOf(ws), "the import fills a new project of the second workspace's own");

  const again = anno(moved, ["export-project", "--out", join(moved, "again.json")]);
  assert.equal(again.status, 0, again.stderr);
  assert.deepEqual(readFileSync(join(moved, "again.json")), readFileSync(backup));
});

test("smoke: a workspace with no project is refused by a report, and the refusal creates nothing", () => {
  const refused = anno(fresh, ["evid-disagreements"]);
  assert.notEqual(refused.status, 0);
  assert.match(refused.stderr, /has no annotation project yet/);
  assert.equal(existsSync(join(fresh, ".c64-re-tools")), false);
});
