#!/usr/bin/env node
// completeness-report.test.mjs -- Tier 1 (pure unit) coverage for the
// decomposition-completeness report (phase 45 plan 45-01, task 3).
//
// PURE UNIT TESTS ONLY, over the exported `buildCompletenessReport()` /
// `renderCompletenessReport()` / `isSurvivorName()` -- fed synthetic,
// hand-written literal records, never a live store, never VICE, never the
// resolved MCP module. This file always runs under CI's
// `node --test 'src/skills/*/scripts/*.test.mjs'` glob, which has no VICE
// install at all.
//
// FROZEN-REGISTRY POSTURE (mirrors anno-verb-coverage.test.ts:33-44): the
// synthetic records below are hand-written, deliberately NOT derived from
// the module under test. A fixture generated by
// `buildCompletenessReport()`/`renderCompletenessReport()` themselves would
// make every assertion below a tautology that passes no matter what the
// renderer does.
//
// The LIVE end-to-end tier (a real derived store, a real live execution run,
// a real `anno evid-disagreements` answer) belongs to plan 45-04's
// planted-RED control; it is deliberately NOT built here.
import { test } from "node:test";
import assert from "node:assert/strict";

import { buildCompletenessReport, renderCompletenessReport, isSurvivorName, MissingDisagreementInputError } from "./completeness-report.mjs";

/** A complete, synthetic-but-plausible answer shape, mirroring exactly what
 * `anno decomp-completeness --json` prints -- hand-written, not derived from
 * a live run. */
function completeAnswer(overrides = {}) {
  return {
    store: "/workspace/.c64-re-tools/tracer.annostore",
    fixture: "dxa/tracer.prg",
    executionDisposition: "executed",
    notExecutedReason: null,
    byteCensus: { byType: { byte: 15, code: 6 }, undefinedCount: 0, denominator: 21 },
    survivors: [],
    disagreementInput: {
      disagreements: [],
      disagreementCount: 0,
      agreementCount: 3,
      blockCoveredNeverObservedCount: 18,
      observedOutsideAnyBlockCount: 1991,
      observedAtUndefinedBlockCount: 0,
      denominator: 21,
      positiveClass: "code",
      tier: "runtime-observed",
      runIdentity: { imageSha256: "a".repeat(64), argvDigest: "b".repeat(64), seed: "fixed-seed" },
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Test 1: absent disagreementInput throws MissingDisagreementInputError,
// and the message names --disagreements literally.
// ---------------------------------------------------------------------------
test("renderCompletenessReport() throws MissingDisagreementInputError naming --disagreements when disagreementInput is absent", () => {
  const answer = completeAnswer();
  delete answer.disagreementInput;
  const report = buildCompletenessReport(answer);
  assert.throws(
    () => renderCompletenessReport(report),
    (err) => {
      assert.ok(err instanceof MissingDisagreementInputError, "must throw MissingDisagreementInputError specifically");
      assert.match(err.message, /--disagreements/, "the thrown message must name the --disagreements option literally");
      return true;
    },
  );
});

// ---------------------------------------------------------------------------
// Test 2: disagreementInput present but runIdentity missing throws the same
// named error -- an empty disagreement array alone is not enough to render.
// ---------------------------------------------------------------------------
test("renderCompletenessReport() throws the same named error when disagreementInput has no complete runIdentity", () => {
  const answer = completeAnswer();
  delete answer.disagreementInput.runIdentity;
  const report = buildCompletenessReport(answer);
  assert.throws(
    () => renderCompletenessReport(report),
    (err) => {
      assert.ok(err instanceof MissingDisagreementInputError);
      assert.match(err.message, /--disagreements/);
      return true;
    },
  );

  // A partial runIdentity (missing one of the three fields) must refuse too.
  const partial = completeAnswer();
  partial.disagreementInput.runIdentity = { imageSha256: "a".repeat(64), argvDigest: "b".repeat(64) };
  const partialReport = buildCompletenessReport(partial);
  assert.throws(() => renderCompletenessReport(partialReport), MissingDisagreementInputError);
});

// ---------------------------------------------------------------------------
// Test 3: a complete synthetic answer renders a DISAGREEMENTS heading, a
// denominator beside every count, and no % character anywhere.
// ---------------------------------------------------------------------------
test("renderCompletenessReport() with a complete answer renders a DISAGREEMENTS heading, a denominator beside every count, and no percentage character", () => {
  const report = buildCompletenessReport(completeAnswer());
  const text = renderCompletenessReport(report);
  assert.match(text, /DISAGREEMENTS/);
  assert.match(text, /AGREEMENT: 3 of 21/);
  assert.match(text, /NO OBSERVATION: 18 of 21/);
  assert.match(text, /BYTE CENSUS \(denominator 21\)/);
  assert.ok(!text.includes("%"), "the rendered report must never contain a percentage, rate or combined figure");
});

// ---------------------------------------------------------------------------
// Test 4: the survivor predicate is anchored and case-sensitive -- l_0810 IS
// a survivor, L_0810 is NOT (anno-coverage.test.ts's own L_ precedent).
// ---------------------------------------------------------------------------
test("isSurvivorName() is anchored and case-sensitive: l_0810 is a survivor, L_0810 is not", () => {
  assert.equal(isSurvivorName("l_0810"), true);
  assert.equal(isSurvivorName("L_0810"), false);
  // The eleven AUTO_NAME_PREFIX_RE prefixes, spot-checked.
  assert.equal(isSurvivorName("p_1234"), true);
  assert.equal(isSurvivorName("s_0820"), true);
  assert.equal(isSurvivorName("S_0820"), false);
  // dxa's own real lNNNN shape (no underscore) and Ghidra's FUN_XXXX shape.
  assert.equal(isSurvivorName("l810"), true);
  assert.equal(isSurvivorName("FUN_1000"), true);
  assert.equal(isSurvivorName("fun_1000"), false);
  // A legitimate authored name that merely starts with a covered letter must
  // NOT be swept in by an unanchored match.
  assert.equal(isSurvivorName("player_x_pos"), false);
  assert.equal(isSurvivorName("bank_switch_handler"), false);
});

// ---------------------------------------------------------------------------
// Test 5: a not-executed manifest entry renders a NOT EXECUTED line carrying
// the entry's own reason; a fixture missing from the manifest is never
// rendered as executed (this is exercised at the buildCompletenessReport()
// layer -- the verb itself refuses a genuinely unlisted fixture, so this
// tier asserts the RENDER shape for a fixture the verb already classified
// not-executed).
// ---------------------------------------------------------------------------
test("a not-executed fixture renders a NOT EXECUTED line carrying its own reason, never a clean bill of health", () => {
  const answer = completeAnswer({
    fixture: "dxa/basic-stub.prg",
    executionDisposition: "not-executed",
    notExecutedReason: "a 12-byte canonical BASIC stub followed by arbitrary bytes -- there is nothing real to execute",
  });
  const report = buildCompletenessReport(answer);
  const text = renderCompletenessReport(report);
  assert.match(text, /NOT EXECUTED/);
  assert.match(text, /nothing real to execute/);
  assert.ok(!text.includes("EXECUTED: this fixture was run"), "a not-executed fixture must never also print the executed line");
});

// ---------------------------------------------------------------------------
// Additional coverage: buildCompletenessReport() itself.
// ---------------------------------------------------------------------------
test("buildCompletenessReport() throws a plain Error (not MissingDisagreementInputError) on a non-object answer", () => {
  assert.throws(() => buildCompletenessReport(null), (err) => {
    assert.ok(!(err instanceof MissingDisagreementInputError));
    return true;
  });
  assert.throws(() => buildCompletenessReport("not an object"));
});

test("buildCompletenessReport() defaults survivors to an empty array when absent, and preserves it when present", () => {
  const withoutSurvivors = completeAnswer();
  delete withoutSurvivors.survivors;
  assert.deepEqual(buildCompletenessReport(withoutSurvivors).survivors, []);

  const withSurvivors = completeAnswer({ survivors: [{ address: 0x0810, name: "l_0810" }] });
  assert.deepEqual(buildCompletenessReport(withSurvivors).survivors, [{ address: 0x0810, name: "l_0810" }]);
});
